const express = require('express');
const router = express.Router();

// ─── Dummy Doctors Data (no DB dependency) ───
const DOCTORS = [
  {
    _id: 'd1',
    user: { firstName: 'Priya', lastName: 'Sharma' },
    specialization: 'Cardiology',
    experience: 14,
    averageRating: 4.9,
    totalReviews: 127,
    consultationFee: 1200,
    city: 'Mumbai',
    bio: '💙 Expert in heart care with 14+ years experience.\n✨ Specializes in interventional cardiology & minimally invasive procedures.\n🏅 Fellow of the American College of Cardiology.\n🩺 Passionate about preventive cardiac wellness.',
    education: ['MD - AIIMS Delhi', 'DM Cardiology - AIIMS', 'Fellowship - Cleveland Clinic, USA'],
    languages: ['English', 'Hindi', 'Marathi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face' },
    address: 'Breach Candy Hospital, 60A Bhulabhai Desai Rd, Mumbai 400026',
    lat: 18.9710,
    lng: 72.8054,
  },
  {
    _id: 'd2',
    user: { firstName: 'Rajesh', lastName: 'Kapoor' },
    specialization: 'Cardiology',
    experience: 20,
    averageRating: 4.8,
    totalReviews: 289,
    consultationFee: 1500,
    city: 'Delhi',
    bio: '❤️ 20 years of saving hearts — one beat at a time.\n🔬 Pioneer in robotic cardiac surgery in India.\n📚 Published 50+ research papers in leading journals.\n💪 Advocates for stress-free living & heart health.',
    education: ['MBBS - Maulana Azad Medical College', 'MS, MCh - AIIMS Delhi'],
    languages: ['English', 'Hindi', 'Punjabi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face' },
    address: 'Fortis Escorts Heart Institute, Okhla Rd, New Delhi 110025',
    lat: 28.5672,
    lng: 77.2789,
  },
  {
    _id: 'd3',
    user: { firstName: 'Aisha', lastName: 'Patel' },
    specialization: 'Orthopedics',
    experience: 11,
    averageRating: 4.7,
    totalReviews: 89,
    consultationFee: 800,
    city: 'Mumbai',
    bio: '🦴 Sports medicine specialist with a passion for movement.\n⚡ Team physician for IPL & national athletes.\n🏆 Expert in ACL reconstruction & joint replacement.\n🌟 Known for gentle approach & fast recovery protocols.',
    education: ['MBBS - Grant Medical College Mumbai', 'MS Ortho - KEM Hospital', 'Fellowship - HSS New York'],
    languages: ['English', 'Hindi', 'Gujarati'],
    isAvailableToday: false,
    nextAvailable: 'Tomorrow',
    photo: { url: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop&crop=face' },
    address: 'Kokilaben Hospital, Rao Saheb Achutrao Patwardhan Marg, Mumbai 400053',
    lat: 19.1310,
    lng: 72.8265,
  },
  {
    _id: 'd4',
    user: { firstName: 'Vikram', lastName: 'Mehta' },
    specialization: 'Neurology',
    experience: 18,
    averageRating: 4.9,
    totalReviews: 315,
    consultationFee: 1400,
    city: 'Bangalore',
    bio: '🧠 Leading neurologist specializing in movement disorders.\n🔬 Published 40+ peer-reviewed papers on neurodegeneration.\n💡 Pioneer in deep brain stimulation therapy in India.\n🎓 Trained at Mayo Clinic & Johns Hopkins.',
    education: ['MBBS - St. Johns Medical College', 'MD Neurology - NIMHANS', 'Fellowship - Mayo Clinic USA'],
    languages: ['English', 'Hindi', 'Kannada'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face' },
    address: 'Manipal Hospital, HAL Airport Rd, Bangalore 560017',
    lat: 12.9592,
    lng: 77.6474,
  },
  {
    _id: 'd5',
    user: { firstName: 'Sofia', lastName: 'D\'Souza' },
    specialization: 'Neurology',
    experience: 9,
    averageRating: 4.6,
    totalReviews: 64,
    consultationFee: 900,
    city: 'Mumbai',
    bio: '🧠 Passionate about unlocking the mysteries of the brain.\n✨ Specializes in epilepsy, migraines & stroke rehabilitation.\n📖 Author of bestselling book on brain wellness.\n🌈 Believes in holistic neurological care.',
    education: ['MBBS - KEM Hospital Mumbai', 'MD Neurology - Bombay Hospital', 'Training - UCSF'],
    languages: ['English', 'Hindi', 'Konkani'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop&crop=face' },
    address: 'Hinduja Hospital, Veer Savarkar Marg, Mumbai 400016',
    lat: 19.0269,
    lng: 72.8407,
  },
  {
    _id: 'd6',
    user: { firstName: 'Arjun', lastName: 'Reddy' },
    specialization: 'Oncology',
    experience: 22,
    averageRating: 4.9,
    totalReviews: 402,
    consultationFee: 2000,
    city: 'Delhi',
    bio: '🎗️ 22 years dedicated to fighting cancer.\n🔬 Pioneer in immunotherapy treatments in South Asia.\n🏥 Director of Cancer Research at Tata Memorial.\n💛 Every patient is a warrior — and I stand with them.',
    education: ['MBBS - AIIMS Delhi', 'MD, DM Oncology - Tata Memorial', 'Fellowship - MD Anderson USA'],
    languages: ['English', 'Hindi', 'Telugu'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face' },
    address: 'Rajiv Gandhi Cancer Institute, Sector 5, Rohini, Delhi 110085',
    lat: 28.7342,
    lng: 77.1143,
  },
  {
    _id: 'd7',
    user: { firstName: 'Meera', lastName: 'Iyer' },
    specialization: 'Oncology',
    experience: 15,
    averageRating: 4.8,
    totalReviews: 178,
    consultationFee: 1800,
    city: 'Chennai',
    bio: '🎗️ Dedicated to making cancer treatment more human.\n✨ Expert in breast cancer & precision oncology.\n🌸 Combines cutting-edge science with compassionate care.\n📚 40+ publications in international journals.',
    education: ['MBBS - Madras Medical College', 'MD Pathology, DM Oncology - CMC Vellore'],
    languages: ['English', 'Tamil', 'Hindi'],
    isAvailableToday: false,
    nextAvailable: 'Wednesday',
    photo: { url: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&h=400&fit=crop&crop=face' },
    address: 'Apollo Cancer Centre, Greams Rd, Chennai 600006',
    lat: 13.0604,
    lng: 80.2526,
  },
  {
    _id: 'd8',
    user: { firstName: 'Sameer', lastName: 'Khan' },
    specialization: 'Dermatology',
    experience: 8,
    averageRating: 4.7,
    totalReviews: 92,
    consultationFee: 700,
    city: 'Mumbai',
    bio: '✨ Your skin tells your story — let me help it glow.\n🔬 Expert in melanoma detection & cosmetic dermatology.\n💆 Specializes in anti-aging, acne & laser treatments.\n🌿 Advocates for natural skincare routines.',
    education: ['MBBS - Seth GS Medical College', 'MD Dermatology - KEM Hospital'],
    languages: ['English', 'Hindi', 'Urdu'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face' },
    address: 'Jaslok Hospital, 15 Dr G Deshmukh Marg, Mumbai 400026',
    lat: 18.9714,
    lng: 72.8105,
  },
  {
    _id: 'd9',
    user: { firstName: 'Ananya', lastName: 'Gupta' },
    specialization: 'Dermatology',
    experience: 12,
    averageRating: 4.8,
    totalReviews: 156,
    consultationFee: 600,
    city: 'Delhi',
    bio: '🌟 Making every skin type feel confident & beautiful.\n💎 Expert in vitiligo, psoriasis & cosmetic procedures.\n🧪 Research-driven approach with cutting-edge treatments.\n🎯 12 years of transforming skin health.',
    education: ['MBBS - Lady Hardinge Medical College', 'MD Dermatology - Safdarjung Hospital'],
    languages: ['English', 'Hindi', 'Bengali'],
    isAvailableToday: false,
    nextAvailable: 'Thursday',
    photo: { url: 'https://images.unsplash.com/photo-1643297654416-05795d62e39c?w=400&h=400&fit=crop&crop=face' },
    address: 'Max Super Speciality Hospital, Saket, New Delhi 110017',
    lat: 28.5280,
    lng: 77.2142,
  },
  {
    _id: 'd10',
    user: { firstName: 'Rohan', lastName: 'Deshmukh' },
    specialization: 'General Surgery',
    experience: 25,
    averageRating: 4.9,
    totalReviews: 430,
    consultationFee: 1000,
    city: 'Mumbai',
    bio: '🔪 25 years of precision surgical excellence.\n🏥 Chief of Surgery at Lilavati Hospital.\n⚡ Expert in laparoscopic & robotic surgery.\n🌟 Known for zero-complication track record.',
    education: ['MBBS - BJ Medical College', 'MS General Surgery - KEM', 'Fellowship - Johns Hopkins'],
    languages: ['English', 'Hindi', 'Marathi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=400&h=400&fit=crop&crop=face' },
    address: 'Lilavati Hospital, A-791 Bandra Reclamation, Mumbai 400050',
    lat: 19.0509,
    lng: 72.8294,
  },
  {
    _id: 'd11',
    user: { firstName: 'Kavita', lastName: 'Nair' },
    specialization: 'Endocrinology',
    experience: 10,
    averageRating: 4.6,
    totalReviews: 73,
    consultationFee: 800,
    city: 'Bangalore',
    bio: '🦋 Hormone health is the key to everything.\n💉 Specializes in diabetes, thyroid & PCOS management.\n🌿 Holistic approach — meds, nutrition & lifestyle combined.\n😊 Patients describe her as warm & thorough.',
    education: ['MBBS - Bangalore Medical College', 'MD Medicine, DM Endocrinology - AIIMS'],
    languages: ['English', 'Hindi', 'Malayalam'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&h=400&fit=crop&crop=face' },
    address: 'Narayana Health City, Bommasandra, Bangalore 560099',
    lat: 12.8003,
    lng: 77.6867,
  },
  {
    _id: 'd12',
    user: { firstName: 'Farid', lastName: 'Sheikh' },
    specialization: 'Gastroenterology',
    experience: 15,
    averageRating: 4.7,
    totalReviews: 134,
    consultationFee: 1100,
    city: 'Mumbai',
    bio: '🫁 Your gut health is your superpower.\n🔬 Pioneer in capsule endoscopy techniques in India.\n🏅 Expert in IBD, liver diseases & advanced endoscopy.\n📖 Dedicated to patient education & preventive GI care.',
    education: ['MBBS - Grant Medical College', 'MD, DM Gastro - AIIMS', 'Fellowship - UCLA Medical Center'],
    languages: ['English', 'Hindi', 'Urdu'],
    isAvailableToday: false,
    nextAvailable: 'Friday',
    photo: { url: 'https://images.unsplash.com/photo-1666214280557-f1b5022eb634?w=400&h=400&fit=crop&crop=face' },
    address: 'Bombay Hospital, 12 New Marine Lines, Mumbai 400020',
    lat: 18.9432,
    lng: 72.8275,
  },
  {
    _id: 'd13',
    user: { firstName: 'Neha', lastName: 'Verma' },
    specialization: 'Pediatrics',
    experience: 13,
    averageRating: 4.8,
    totalReviews: 210,
    consultationFee: 600,
    city: 'Delhi',
    bio: '👶 Every child deserves the best start in life.\n🌈 13 years of caring for tiny humans with big smiles.\n💉 Expert in childhood development & vaccinations.\n💝 Loved by kids and parents alike!',
    education: ['MBBS - MAMC Delhi', 'MD Pediatrics - Kalawati Saran Hospital'],
    languages: ['English', 'Hindi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&h=400&fit=crop&crop=face' },
    address: 'Sir Ganga Ram Hospital, Rajinder Nagar, New Delhi 110060',
    lat: 28.6408,
    lng: 77.1869,
  },
  {
    _id: 'd14',
    user: { firstName: 'Siddharth', lastName: 'Joshi' },
    specialization: 'Pediatrics',
    experience: 9,
    averageRating: 4.7,
    totalReviews: 98,
    consultationFee: 500,
    city: 'Mumbai',
    bio: '🧒 Making doctor visits fun & stress-free for kids.\n🎯 Specializes in neonatal care & childhood allergies.\n🌟 Uses play therapy to ease anxiety.\n😄 The doctor kids WANT to visit!',
    education: ['MBBS - TN Medical College', 'DCH, MD Pediatrics - Wadia Hospital'],
    languages: ['English', 'Hindi', 'Marathi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&h=400&fit=crop&crop=face' },
    address: 'Wadia Hospital, Acharya Donde Marg, Parel, Mumbai 400012',
    lat: 19.0022,
    lng: 72.8414,
  },
  {
    _id: 'd15',
    user: { firstName: 'Lakshmi', lastName: 'Sundaram' },
    specialization: 'Psychiatry',
    experience: 16,
    averageRating: 4.9,
    totalReviews: 241,
    consultationFee: 1000,
    city: 'Chennai',
    bio: '🧘 Mental health is not a luxury — it\'s a necessity.\n💭 Expert in anxiety, depression & PTSD.\n📖 Author of 2 bestselling books on mental wellness.\n🌸 Integrates CBT with mindfulness practices.',
    education: ['MBBS - Madras Medical College', 'MD Psychiatry - NIMHANS'],
    languages: ['English', 'Tamil', 'Hindi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face' },
    address: 'Apollo Hospitals, Greams Lane, Chennai 600006',
    lat: 13.0612,
    lng: 80.2534,
  },
  {
    _id: 'd16',
    user: { firstName: 'Aman', lastName: 'Bhatia' },
    specialization: 'Psychiatry',
    experience: 11,
    averageRating: 4.7,
    totalReviews: 145,
    consultationFee: 900,
    city: 'Delhi',
    bio: '🧠 Breaking the stigma around mental health, one session at a time.\n💡 Specializes in addiction therapy & OCD treatment.\n🎧 Offers both in-person & virtual sessions.\n🤝 Creating safe spaces to heal.',
    education: ['MBBS - UCMS Delhi', 'MD Psychiatry - IHBAS Delhi'],
    languages: ['English', 'Hindi', 'Punjabi'],
    isAvailableToday: false,
    nextAvailable: 'Monday',
    photo: { url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face' },
    address: 'VIMHANS Hospital, 1 Nehru Nagar, New Delhi 110065',
    lat: 28.5719,
    lng: 77.2533,
  },
  {
    _id: 'd17',
    user: { firstName: 'Divya', lastName: 'Menon' },
    specialization: 'Ophthalmology',
    experience: 14,
    averageRating: 4.8,
    totalReviews: 189,
    consultationFee: 900,
    city: 'Bangalore',
    bio: '👁️ Helping you see the world with crystal clarity.\n🔬 Expert in LASIK, cataract surgery & retinal care.\n✨ Over 10,000+ successful eye procedures.\n🌟 Known for gentle technique & precision.',
    education: ['MBBS - Kasturba Medical College', 'MS Ophthalmology - Sankara Nethralaya'],
    languages: ['English', 'Hindi', 'Malayalam'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=400&h=400&fit=crop&crop=face' },
    address: 'Sankara Eye Hospital, Kundalahalli, Bangalore 560037',
    lat: 12.9609,
    lng: 77.7137,
  },
  {
    _id: 'd18',
    user: { firstName: 'Ravi', lastName: 'Shankar' },
    specialization: 'Pulmonology',
    experience: 17,
    averageRating: 4.8,
    totalReviews: 167,
    consultationFee: 1000,
    city: 'Delhi',
    bio: '🫁 Breathe easy — your lungs are in expert hands.\n🏅 17 years treating asthma, COPD & sleep disorders.\n🔬 Certified in critical care & interventional pulmonology.\n💨 Champion of clean air & lung health awareness.',
    education: ['MBBS - MAMC Delhi', 'MD Pulmonary Medicine - VPCI Delhi', 'Fellowship - Royal Brompton UK'],
    languages: ['English', 'Hindi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face' },
    address: 'Medanta - The Medicity, CH Baktawar Singh Rd, Gurugram 122001',
    lat: 28.4395,
    lng: 77.0425,
  },
  {
    _id: 'd19',
    user: { firstName: 'Tanya', lastName: 'Chatterjee' },
    specialization: 'Orthopedics',
    experience: 10,
    averageRating: 4.7,
    totalReviews: 112,
    consultationFee: 750,
    city: 'Bangalore',
    bio: '🦴 Movement is medicine — and I help you move pain-free.\n⚡ Specializes in spine surgery & sports injuries.\n🏃 Works with marathon runners & fitness athletes.\n🌟 Minimally invasive techniques for faster recovery.',
    education: ['MBBS - JIPMER Puducherry', 'MS Ortho - CMC Vellore'],
    languages: ['English', 'Hindi', 'Bengali'],
    isAvailableToday: false,
    nextAvailable: 'Tuesday',
    photo: { url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face' },
    address: 'Sparsh Hospital, Infantry Rd, Bangalore 560001',
    lat: 12.9812,
    lng: 77.6010,
  },
  {
    _id: 'd20',
    user: { firstName: 'Karthik', lastName: 'Raman' },
    specialization: 'General Surgery',
    experience: 19,
    averageRating: 4.8,
    totalReviews: 278,
    consultationFee: 1100,
    city: 'Chennai',
    bio: '🔪 Precision. Perfection. Patient-first.\n🏥 19 years of surgical excellence.\n⚡ Expert in bariatric surgery & hernia repair.\n🌟 Trusted by thousands for life-changing procedures.',
    education: ['MBBS - Stanley Medical College', 'MS General Surgery - Govt General Hospital Chennai'],
    languages: ['English', 'Tamil', 'Hindi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face' },
    address: 'MIOT International, Mount Poonamallee Rd, Chennai 600089',
    lat: 13.0283,
    lng: 80.1707,
  },
  {
    _id: 'd21',
    user: { firstName: 'Meera', lastName: 'Nair' },
    specialization: 'Dermatology',
    experience: 10,
    averageRating: 4.7,
    totalReviews: 195,
    consultationFee: 900,
    city: 'Bangalore',
    bio: '✨ Your skin tells a story — let me help write a beautiful one.\n🔬 10 years specializing in clinical & cosmetic dermatology.\n💊 Expert in acne, pigmentation, eczema & anti-aging treatments.\n🌿 Advocate of gentle, science-backed skincare routines.\n🏆 Award-winning dermatologist with 195+ glowing reviews.',
    education: ['MBBS - Kasturba Medical College', 'MD Dermatology - St. John\'s Medical College Bangalore'],
    languages: ['English', 'Malayalam', 'Kannada', 'Hindi'],
    isAvailableToday: true,
    nextAvailable: null,
    photo: { url: 'https://images.unsplash.com/photo-1594824476967-48c8b964ac31?w=400&h=400&fit=crop&crop=face' },
    address: 'Manipal Hospital, Old Airport Road, Bangalore 560017',
    lat: 12.9569,
    lng: 77.6244,
  },
];

// GET /api/v1/doctors — list with optional filters
router.get('/', (req, res) => {
  const { search, specialization, city, availableToday } = req.query;
  let results = [...DOCTORS];

  if (search) {
    const q = search.toLowerCase();
    results = results.filter(
      (d) =>
        d.user.firstName.toLowerCase().includes(q) ||
        d.user.lastName.toLowerCase().includes(q) ||
        d.specialization.toLowerCase().includes(q)
    );
  }

  if (specialization) {
    results = results.filter(
      (d) => d.specialization.toLowerCase() === specialization.toLowerCase()
    );
  }

  if (city) {
    results = results.filter(
      (d) => d.city.toLowerCase() === city.toLowerCase()
    );
  }

  if (availableToday === 'true') {
    results = results.filter((d) => d.isAvailableToday);
  }

  const { sort, limit } = req.query;
  if (sort === '-averageRating') {
    results.sort((a, b) => (b.averageRating || 0) - (a.averageRating || 0));
  }
  if (limit) {
    results = results.slice(0, parseInt(limit, 10) || results.length);
  }

  res.json({ success: true, count: results.length, data: results });
});

// GET /api/v1/doctors/:id — single doctor
router.get('/:id', (req, res) => {
  const doctor = DOCTORS.find((d) => d._id === req.params.id);
  if (!doctor) {
    return res.status(404).json({ success: false, error: 'Doctor not found' });
  }
  res.json({ success: true, data: doctor });
});

module.exports = router;